version: "3.9"
services:
    app:
        build: .
        image: currency_converter:latest
        working_dir: /app
        depends_on:
            - postgres
    postgres:
        image: postgres:13.3
        environment:
            POSTGRES_PASSWORD: secure_password
